website:
  title: "Interests"
  sidebar:
    style: "docked"
    search: true
    contents:
      - href: armed_conflict.qmd
        text: Armed Conflicts
      - href: mass.qmd
        text: MA Property Tax Rates
      - href: investment_calculator.qmd
        text: Investment Calculator