project:
  type: website
  output-dir: docs

website:
  title: "Interests"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: armed_conflict.qmd
        text: Armed Conflicts

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



